### ISSUE TITLE
Critical vulnerability in vm2 dependency

### ISSUE THREAD

**Issue by toastyghost** [TooTallNate/node-degenerator#15]
Just got this from Snyk:

![vm2-vuln](https://user-images.githubusercontent.com/204219/153505327-7aca3a9e-0e52-493a-b182-2ab668cdefab.png)

Fix is straightforward, just update the package and republish

**Comment by robdmoore** [comment]
For some reason I'm not able to use `npm-force-resolutions` to force this dependency to upgrade like I normally would.

This is a deep depedency of (I'm sure many other libraries too) aws-cdk.

Any change the PR can get merged and released given the criticality of this vulnerability @TooTallNate 🙏?

**Comment by robdmoore** [comment]
Thanks @TooTallNate!
