### ISSUE TITLE
npm install degenerator fails "136 error git clone https://github.com/ariya/esprima.git"

### ISSUE THREAD

**Issue by gitmft** [TooTallNate/node-degenerator#5]
i tried both behind firewall and outside.

below is snippet from npn-debug.log

130 silly cache afterAdd escodegen@1.3.3
131 verbose afterAdd /home/dberry/.npm/escodegen/1.3.3/package/package.json not in flight; writing
132 silly cache afterAdd ast-types@0.3.38
133 verbose afterAdd /home/dberry/.npm/ast-types/0.3.38/package/package.json not in flight; writing
134 verbose afterAdd /home/dberry/.npm/escodegen/1.3.3/package/package.json written
135 verbose afterAdd /home/dberry/.npm/ast-types/0.3.38/package/package.json written
136 error git clone https://github.com/ariya/esprima.git Initialized empty Git repository in /home/dberry/.npm/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/
136 error git clone https://github.com/ariya/esprima.git
136 error git clone https://github.com/ariya/esprima.git error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/ariya/esprima.git/info/refs
136 error git clone https://github.com/ariya/esprima.git
136 error git clone https://github.com/ariya/esprima.git fatal: HTTP request failed
137 verbose about to build /scratch/dberry/tmp/omftc/node_modules/degenerator
138 verbose unlock done using /home/dberry/.npm/_locks/degenerator-285c3e6a25d774f9.lock for /scratch/dberry/tmp/omftc/node_modules/degenerator
139 verbose stack Error: Command failed: git clone --template=/home/dberry/.npm/_git-remotes/_templates --mirror https://github.com/ariya/esprima.git /home/dberry/.npm/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9
139 verbose stack error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/ariya/esprima.git/info/refs
139 verbose stack
139 verbose stack fatal: HTTP request failed
139 verbose stack
139 verbose stack     at ChildProcess.exithandler (child_process.js:744:12)
139 verbose stack     at ChildProcess.emit (events.js:110:17)
139 verbose stack     at maybeClose (child_process.js:1008:16)
139 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
140 verbose cwd /scratch/dberry/tmp/omftc
141 error Linux 3.8.13-44.1.1.el6uek.x86_64
142 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "degenerator"

**Comment by bojand** [comment]
Hello, the reference to a deleted branch is is effecting a lot of dependancies of this package, and all the way down the chain. including pac-proxy-agent and proxy-agent.

https://github.com/npm/npm/issues/8641
https://github.com/TooTallNate/node-proxy-agent/issues/7

and more...

**Comment by chazmo03** [comment]
I second that. It's causing me ample grief this morning.

**Comment by cristiandouce** [comment]
+1
It's made my monday morning not as happy as usual :grinning: hahaha

**Comment by TooTallNate** [comment]
Should be fixed in v1.0.2.
