### ISSUE TITLE
0.x.x dependency on ast-types pulls in breaking changes

### ISSUE THREAD

**Issue by chrisakers** [TooTallNate/node-degenerator#9]
[17 days ago](https://github.com/benjamn/ast-types/commit/e7278505892c2277b090966f9a9045bdb3559098) ast-types started using arrow functions.

Arrow functions are not supported in node<4. So apps running in node<4 which are dependent on node-degenerator are now starting to fail with syntax errors.

For me it has hit our CI pipeline for our old apps that are using node 0.10 and that are using your node-proxy-agent library.

Is there a possibility of locking in a specific version of ast-types prior to the breaking change?

**Comment by chrisakers** [comment]
Maybe we just need a release? I see that the dependency is set to a value other than "0.x.x" in package.json. But there hasn't been a release since the dependency versions have changed.

**Comment by TooTallNate** [comment]
I'm gonna close this one since Node 4 is rather old at this point. But also, if this is still relevant for you I suggest using a lockfile to pin a version of `ast-types` that is still compatible with your environment.
